### ISSUE TITLE
Timestamps have wrong date when inserting data using Postgres JDBC

### ISSUE THREAD

**Issue by null-dev** [questdb/questdb#1359]
**Describe the bug**
Timestamps insert with the wrong date over Postgres JDBC.

**To Reproduce**
1. Unzip and run the attached Kotlin script using the following command: `kotlin questdb-timestamp-fail.main.kts`. If you do not have Kotlin installed you can transcribe the script to Java instead, it should be very simple to do.
2. Observe that the original `java.sql.Timestamp` we insert into the database differs drastically from the `java.sql.Timestamp` object we get from the database when querying our inserted data.
3. The above can also be observed from the QuestDB web UI as well.

**Expected behavior**
The timestamp we insert into the database should match the timestamp we get when we query for the inserted data.

**Environment (please complete the following information):**
 - OS: Arch Linux 5.14.7-zen1-1-zen x86_64
 - Browser: Firefox Developer 93.0b9 (64-bit)
 - QuestDB Version: 6.0.6 (docker). I've also tested 6.0.5 and the issue is present there as well.
 - Postgres driver version: PostgreSQL JDBC Driver 42.2.24 (https://jdbc.postgresql.org/)
 - JVM version: `AdoptOpenJDK version "17"`

**Additional context**
I have not ruled out whether or not this is a bug in the Java Postgres JDBC driver.

**Attachments:**
[script.zip](https://github.com/questdb/questdb/files/7230351/script.zip)

**Comment by bluestreak01** [comment]
There is example under Java tab on how to insert timestamps. The unit of measure is micros, your example supplies millis.

https://questdb.io/docs/develop/insert-data#postgres-compatibility

**Comment by null-dev** [comment]
@bluestreak01 Right, but `java.sql.Timestamp` is supposed to be constructed with milliseconds (ref: https://docs.oracle.com/javase/8/docs/api/java/sql/Timestamp.html#Timestamp-long-). Constructing the Timestamp object using microseconds is confusing and also makes debugging harder because when I try to `println` it, the `toString` value becomes something like: `53710-08-02 12:04:13.0`. It also means I can no longer construct a `java.sql.Timestamp` object from a string.

And finally, the biggest issue is that I can no longer take a Timestamp object that I got from querying the the DB and re-insert it into the DB. Example:

If I had a database with the following row:

| test |
| - |
| 2021-09-27 16:45:03.202 |

and I ran the following code:

```
val queryResult = connection.prepareStatement("SELECT * FROM testing;").executeQuery()
queryResult.next()
val afterTimestamp = queryResult.getTimestamp("test")

val insertStatement = connection.prepareStatement("INSERT INTO testing VALUES (?);")
insertStatement.setTimestamp(1, afterTimestamp)
insertStatement.execute()
```

I would get the following new database state:

| test |
| - |
| 2021-09-27 16:45:03.202 |
| 1970-01-19 16:32:55.594 |

Which is extremely confusing because the code simply takes the timestamp from the first row and inserts it into another row at the end of the database.

**Comment by null-dev** [comment]
Actually, nevermind, I just tried to insert a Timestamp object constructed using microseconds and it throws the following error.

E.g. with the following code:

```
val timestamp = Timestamp(System.currentTimeMillis() * 1000)
println("Before: " + timestamp.toString())
val insertStatement = connection.prepareStatement("INSERT INTO testing VALUES (?);")
insertStatement.setTimestamp(1, timestamp)
insertStatement.execute()
```

I get:

```
org.postgresql.util.PSQLException: ERROR: could not parse [value='53710-08-12 10:24:12-04', as=TIMESTAMP, index=0]
  Position: 1
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
        at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
        at Questdb_timestamp_fail_main.<init>(questdb-timestamp-fail.main.kts:39)
```

**Comment by bluestreak01** [comment]
can you please try setting `binaryTransfer` to `true` ?

```
        properties.setProperty("binaryTransfer", Boolean.toString(binary));
```

**Comment by bluestreak01** [comment]
our timestamp resolution is micros, there are not a lot of ways to pass micros across via PG protocol. We have a test that passes timestamp via various means:

https://github.com/questdb/questdb/blob/c2eb8922ff2c6189d5d0d9383847b07dffcfcc1f/core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java#L946

**Comment by null-dev** [comment]
There's an edge case that the test does not catch when we construct a Timestamp like this: `new Timestamp(millis * 1000)`.

When constructing a `Timestamp` object from an accurate source of microseconds, the `Timestamp` represents an epoch time that looks something like this: `1632857409651937`. The driver serializes this `Timestamp` like so: `53713-03-11 14:40:51.937+00`.

If instead we construct a `Timestamp` object from a millisecond source that we convert into microseconds, the `Timestamp` represents an epoch time that looks like: `1632857409651000`. The driver serializes `Timestamp` like so: `53713-03-11 14:40:51+00`.

QuestDB is unable to parse the second case because it gets confused when there is no decimal. To reproduce this, you can change this line https://github.com/questdb/questdb/blob/c2eb8922ff2c6189d5d0d9383847b07dffcfcc1f/core/src/test/java/io/questdb/cutlass/pgwire/PGJobContextTest.java#L969 to `long micros = System.currentTimeMillis() * 1000;`.

Now of course the above issue should probably be fixed but my main gripe is still that needing to construct the Timestamp object with microseconds is confusing. I understand if that is impossible to change due to a technical limitation however.

**Comment by marregui** [comment]
Hi @null-dev 

I have just tested in master, and this code passes (not part of the codebase, but will commit it if you would like me to):

```
 @Test
    public void testTimestamp() throws Exception {
        TestUtils.assertMemoryLeak(() -> {
            try (final PGWireServer ignored = createPGServer(1)) {
                try (final Connection connection = getConnection(false, true)) {
                    connection.setAutoCommit(false);
                    connection.prepareStatement("create table ts (ts timestamp) timestamp(ts) partition by month").execute();
                    connection.prepareStatement("insert into ts (ts) values ('2021-09-27T16:45:03.202345Z')").execute();
                    connection.commit();
                    connection.setAutoCommit(true);

                    Timestamp ts;
                    try (PreparedStatement statement = connection.prepareStatement("ts")) {
                        try (ResultSet rs = statement.executeQuery()) {
                            assertTrue(rs.next());
                            ts = rs.getTimestamp("ts");
                        }
                    }
                    assertEquals("2021-09-27 16:45:03.202345", ts.toString());
                    assertEquals(1632761103202L, ts.getTime());
                    assertEquals(202345000, ts.getNanos());

                    sink.clear();
                    try (PreparedStatement ps = connection.prepareStatement("INSERT INTO ts VALUES (?);")) {
                        // insert the timestamp as we got it from a select ^ ^
                        ps.setTimestamp(1, ts);
                        ps.execute();

                        // insert a timestamp spelling out its construction
                        assertEquals(1632761103202L, ts.getTime());
                        assertEquals(202345000, ts.getNanos());
                        Timestamp newTs = new Timestamp(ts.getTime());
                        newTs.setNanos(ts.getNanos());
                        ps.setTimestamp(1, newTs);
                        ps.execute();

                        // a more convoluted approach
                        long questdbTs = TimestampFormatUtils.parseTimestamp("2021-09-27T16:45:03.202345Z");
                        assertEquals(1632761103202345L, questdbTs);
                        long time = questdbTs / 1000;
                        assertEquals(1632761103202L, time);
                        int nanos = (int)(questdbTs - (int)(questdbTs / 1e6) * 1e6) * 1000;
                        assertEquals(202345000, nanos);
                        Timestamp anotherTs = new Timestamp(time);
                        anotherTs.setNanos(nanos);
                        ps.setTimestamp(1, anotherTs);
                        ps.execute();
                    }

                    try (PreparedStatement statement = connection.prepareStatement("ts")) {
                        sink.clear();
                        try (ResultSet rs = statement.executeQuery()) {
                            assertResultSet(
                                    "ts[TIMESTAMP]\n" +
                                            "2021-09-27 16:45:03.202345\n" +
                                            "2021-09-27 16:45:03.202345\n" +
                                            "2021-09-27 16:45:03.202345\n" +
                                            "2021-09-27 16:45:03.202345\n",
                                    sink,
                                    rs
                            );
                        }
                    }
                    connection.prepareStatement("drop table ts").execute();
                }
            }
        });
    }
```

Things to note:
- We can select a `java.sql.Timestamp` from QuestDB and simply insert it as-is.
- We can spell out a `java.sql.Timestamp` with microsecond precision by setting the nanos appropriately.

```
    long questdbTs = TimestampFormatUtils.parseTimestamp("2021-09-27T16:45:03.202345Z");
    assertEquals(1632761103202345L, questdbTs);
    long time = questdbTs / 1000;
    assertEquals(1632761103202L, time);
    int nanos = (int)(questdbTs - (int)(questdbTs / 1e6) * 1e6) * 1000;
    assertEquals(202345000, nanos);
    Timestamp anotherTs = new Timestamp(time);
    anotherTs.setNanos(nanos);
``` 
Thank you for the report!!. I personally feel this is solved, so I will go ahead and close the issue.

Best regards,

**Comment by null-dev** [comment]
Unfortunately, the issue is still present, I modified two lines in your test: https://gist.github.com/null-dev/0662d7c6fc322542adca7891234691bd/revisions and it no longer passes.

Also, observe how the following test doesn't pass either:

```java
    @Test
    public void testTimestamp() throws Exception {
        TestUtils.assertMemoryLeak(() -> {
            try (final PGWireServer ignored = createPGServer(1)) {
                try (final Connection connection = getConnection(false, true)) {
                    connection.setAutoCommit(false);

                    // Create table
                    connection.prepareStatement("create table ts (ts timestamp) timestamp(ts) partition by month").execute();
                    connection.commit();

                    // Create and insert timestamp
                    Timestamp timestamp = Timestamp.valueOf("2021-09-11 07:29:59.306");
                    PreparedStatement insertStatement = connection.prepareStatement("INSERT INTO ts VALUES (?)");
                    insertStatement.setTimestamp(1, timestamp);
                    insertStatement.execute();
                    connection.commit();

                    // Query for inserted timestamp
                    ResultSet queryResult = connection.prepareStatement("SELECT * FROM ts").executeQuery();
                    queryResult.next();
                    Timestamp afterTimestamp = queryResult.getTimestamp("ts");

                    // Check that timestamps are equal
                    assertEquals(timestamp, afterTimestamp);

                    // Cleanup
                    connection.prepareStatement("drop table ts").execute();
                }
            }
        });
    }
```

**Comment by marregui** [comment]
I see!, indeed, I am having a look at this, will keep you updated, thank you for spotting it!!!!!!!

**Comment by marregui** [comment]
it is a bug, I will attempt to get it fixed/merged this week.

**Comment by marregui** [comment]
hola, I have created a PR with convoluted tests, as I need it to get a better understanding of whether this is indeed a bug, or an artefact of the fact that we use java.sql.Timestamp, which works on millisecond precision and then it internally handles up to nanos precision with setNanos, while QuestDB understands microsecond precision :)
